/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tebakbaku;

/**
 *
 * @author syuja
 */
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
    
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Left = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        Quotes = new javax.swing.JLabel();
        Right = new javax.swing.JPanel();
        RegisterLabel = new javax.swing.JLabel();
        ChooseUsernameLabel = new javax.swing.JLabel();
        ChooseUsernameForm = new javax.swing.JTextField();
        ChoosePasswordLabel = new javax.swing.JLabel();
        ChoosePasswordForm = new javax.swing.JPasswordField();
        ConfirmPasswordLabel = new javax.swing.JLabel();
        ConfirmPasswordForm = new javax.swing.JPasswordField();
        RegisterButton = new javax.swing.JButton();
        LoginButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TebakBaku - Register");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        Left.setBackground(new java.awt.Color(78, 110, 129));
        Left.setPreferredSize(new java.awt.Dimension(400, 500));

        Logo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        Logo.setForeground(new java.awt.Color(255, 255, 255));
        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setText("TebakBaku");

        Quotes.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Quotes.setForeground(new java.awt.Color(255, 255, 255));
        Quotes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Quotes.setText("Pahami Bahasa, Kuasai Kata.");

        javax.swing.GroupLayout LeftLayout = new javax.swing.GroupLayout(Left);
        Left.setLayout(LeftLayout);
        LeftLayout.setHorizontalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(Quotes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        LeftLayout.setVerticalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(Logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Quotes)
                .addContainerGap(277, Short.MAX_VALUE))
        );

        jPanel1.add(Left);
        Left.setBounds(0, 0, 400, 500);

        Right.setBackground(new java.awt.Color(255, 255, 255));

        RegisterLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        RegisterLabel.setForeground(new java.awt.Color(78, 110, 129));
        RegisterLabel.setText("REGISTER");

        ChooseUsernameLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        ChooseUsernameLabel.setForeground(new java.awt.Color(78, 110, 129));
        ChooseUsernameLabel.setText("Choose Username");

        ChooseUsernameForm.setBackground(new java.awt.Color(46, 56, 64));
        ChooseUsernameForm.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        ChooseUsernameForm.setForeground(new java.awt.Color(255, 255, 255));
        ChooseUsernameForm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(46, 56, 64), 2));
        ChooseUsernameForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooseUsernameFormActionPerformed(evt);
            }
        });

        ChoosePasswordLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        ChoosePasswordLabel.setForeground(new java.awt.Color(78, 110, 129));
        ChoosePasswordLabel.setText("Choose Password");

        ChoosePasswordForm.setBackground(new java.awt.Color(46, 56, 64));
        ChoosePasswordForm.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        ChoosePasswordForm.setForeground(new java.awt.Color(255, 255, 255));
        ChoosePasswordForm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(46, 56, 64), 2));
        ChoosePasswordForm.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        ConfirmPasswordLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        ConfirmPasswordLabel.setForeground(new java.awt.Color(78, 110, 129));
        ConfirmPasswordLabel.setText("Confirm Password");

        ConfirmPasswordForm.setBackground(new java.awt.Color(46, 56, 64));
        ConfirmPasswordForm.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        ConfirmPasswordForm.setForeground(new java.awt.Color(255, 255, 255));
        ConfirmPasswordForm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(46, 56, 64), 2));
        ConfirmPasswordForm.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        RegisterButton.setBackground(new java.awt.Color(78, 110, 129));
        RegisterButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        RegisterButton.setForeground(new java.awt.Color(255, 255, 255));
        RegisterButton.setText("Sign Up");
        RegisterButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });

        LoginButton.setBackground(new java.awt.Color(255, 255, 255));
        LoginButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(78, 110, 129));
        LoginButton.setText("Already have an account?");
        LoginButton.setBorder(null);
        LoginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RightLayout = new javax.swing.GroupLayout(Right);
        Right.setLayout(RightLayout);
        RightLayout.setHorizontalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightLayout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightLayout.createSequentialGroup()
                        .addComponent(RegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightLayout.createSequentialGroup()
                        .addComponent(LoginButton)
                        .addGap(119, 119, 119))))
            .addGroup(RightLayout.createSequentialGroup()
                .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RightLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ChooseUsernameLabel)
                            .addComponent(ChooseUsernameForm)
                            .addComponent(ChoosePasswordLabel)
                            .addComponent(ChoosePasswordForm)
                            .addComponent(ConfirmPasswordLabel)
                            .addComponent(ConfirmPasswordForm, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)))
                    .addGroup(RightLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(RegisterLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RightLayout.setVerticalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(RegisterLabel)
                .addGap(28, 28, 28)
                .addComponent(ChooseUsernameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChooseUsernameForm, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ChoosePasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChoosePasswordForm, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ConfirmPasswordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ConfirmPasswordForm, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LoginButton)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jPanel1.add(Right);
        Right.setBounds(400, 0, 400, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getAccessibleContext().setAccessibleName("REGISTER");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChooseUsernameFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooseUsernameFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChooseUsernameFormActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        FrameManager.navigateToLogin(this);
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        // Get user input from the registration form
        String username = ChooseUsernameForm.getText().trim();
        String password = new String(ChoosePasswordForm.getPassword());
        String confirmPassword = new String(ConfirmPasswordForm.getPassword());

        // Check if passwords match
        if (!password.equals(confirmPassword)) {
            // Display an error message if passwords do not match
            JOptionPane.showMessageDialog(this, "Passwords do not match", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Check if the password is at least 6 characters long
        if (password.length() < 6) {
            // Display an error message if the password is too short
            JOptionPane.showMessageDialog(this, "Password must be at least 6 characters long", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Connect to the database
        try (Connection connection = DatabaseHandler.establishConnection()) {
            if (connection != null) {
                boolean registrationSuccessful = DatabaseHandler.registerUser(connection, username, password);

                if (registrationSuccessful) {
                    System.out.println("Register Success.");
                    JOptionPane.showMessageDialog(this, "User registered successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                    // Redirect to the login page
                    FrameManager.navigateToLogin(this);
                } else {
                    JOptionPane.showMessageDialog(this, "Username has been taken!", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Failed to establish a connection to the database.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error connecting to the database", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_RegisterButtonActionPerformed
        public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new Register().setVisible(true);
        });
    }
    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ChoosePasswordForm;
    private javax.swing.JLabel ChoosePasswordLabel;
    private javax.swing.JTextField ChooseUsernameForm;
    private javax.swing.JLabel ChooseUsernameLabel;
    private javax.swing.JPasswordField ConfirmPasswordForm;
    private javax.swing.JLabel ConfirmPasswordLabel;
    private javax.swing.JPanel Left;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Quotes;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JLabel RegisterLabel;
    private javax.swing.JPanel Right;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    // Start of my code
    
}
